services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # mount path relative to the compose file, so it's persisted across sessions
      - ${DB_MOUNT_PATH}:/data/db

  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    command: ["/nsqd", "-broadcast-address", "0.0.0.0", "-lookupd-tcp-address", "lookupd:4160"]
    depends_on:
      - lookupd

  lookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
